import { AssertionError } from "assert"

export function teste (titulo, funcaoTeste) {
  try {
    funcaoTeste()
    console.log(`âœ… ${titulo} passou.`)
  } catch (error) {
    if (error instanceof AssertionError) {
      console.log(`ðŸš¨ ${titulo} deu ruim. \n ${error.message}`)
    }
  }
}